repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.6.3
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  -   id: black
      args: [--line-length=79, --check]
- repo: https://github.com/PyCQA/flake8
  rev: 7.2.0
  hooks:
  -   id: flake8
      args: [--max-line-length=79]
